# Generated by Django 4.1.3 on 2023-01-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="developer",
            name="age",
            field=models.SmallIntegerField(),
        ),
    ]
